# https://taskfile.dev

version: '3'

tasks:
  start-db:
    desc: "Start PostgreSQL database"
    cmds:
      - docker-compose -f deploy\docker-compose-postgres.yml up -d 
      - docker-compose -f deploy\docker-compose-kafka.yml up -d 

  install-migrate:
    desc: "Install the migrate tool"
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  run-migrate:
    desc: "Run database migration"
    cmds:
      - migrate -path ./schema -database 'postgres://postgres:1234@localhost:5432/postgres?sslmode=disable' up
